In [68]:
# get_cell()
# get_city()
# get_dob()
# get_email()
# get_first_name()
# get_full_name()
# get_gender()
# get_id()
# get_id_number()
# get_id_type()
# get_info()
# get_last_name()
# get_login_md5()
# get_login_salt()
# get_login_sha1()
# get_login_sha256()
# get_nat()
# get_password()
# get_phone()
# get_picture()
# get_postcode()
# get_registered()
# get_state()
# get_street()
# get_username()
# get_zipcode()

In [69]:
from randomuser import RandomUser
import pandas as pd

In [70]:
r = RandomUser()

## GENERATE_USERS

In [71]:
some_list = r.generate_users(10)

In [72]:
some_list

[<randomuser.RandomUser at 0x1cdff186540>,
 <randomuser.RandomUser at 0x1cdff187a40>,
 <randomuser.RandomUser at 0x1cdff186c30>,
 <randomuser.RandomUser at 0x1cdff187500>,
 <randomuser.RandomUser at 0x1cdff185010>,
 <randomuser.RandomUser at 0x1cdff187a10>,
 <randomuser.RandomUser at 0x1cdff186b70>,
 <randomuser.RandomUser at 0x1cdff187320>,
 <randomuser.RandomUser at 0x1cdff187c50>,
 <randomuser.RandomUser at 0x1cdff187590>]

In [73]:
name = r.get_full_name()
name

'Marel Hageman'

In [74]:
for user in some_list:
    print(user.get_full_name(), user.get_email(), sep = ':  ')

Adem Recktenwald:  adem.recktenwald@example.com
Constance Mason:  constance.mason@example.com
Tyler Rice:  tyler.rice@example.com
Sofia Bakkan:  sofia.bakkan@example.com
Sander Pedersen:  sander.pedersen@example.com
Matthew Singh:  matthew.singh@example.com
Kick Gort:  kick.gort@example.com
Steve Hayes:  steve.hayes@example.com
Susana Torres:  susana.torres@example.com
Orrin Linker:  orrin.linker@example.com

In [75]:
def get_user():
    users = []
    for user in some_list:
        users.append({"FUll Name" : user.get_full_name(), "Age" : user.get_age(), "Gender" : user.get_gender(), "City" : user.get_city(), "State" : user.get_state(), "Email" : user.get_email(), "Dob" : user.get_dob(), "Picture" : user.get_picture()})
    return pd.DataFrame(users)

In [81]:
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/41.jpg
https://randomuser.me/api/portraits/women/90.jpg
https://randomuser.me/api/portraits/men/12.jpg
https://randomuser.me/api/portraits/women/72.jpg
https://randomuser.me/api/portraits/men/24.jpg
https://randomuser.me/api/portraits/men/36.jpg
https://randomuser.me/api/portraits/men/3.jpg
https://randomuser.me/api/portraits/men/53.jpg
https://randomuser.me/api/portraits/women/10.jpg
https://randomuser.me/api/portraits/men/7.jpg

In [76]:
get_user()

,FUll Name,Age,Gender,City,State,Email,Dob,Picture
0,Adem Recktenwald,35,male,Bad Kötzting,Saarland,adem.recktenwald@example.com,1991-06-24T21:13:29.046Z,https://randomuser.me/api/portraits/men/41.jpg
1,Constance Mason,70,female,Nowra,Western Australia,constance.mason@example.com,1956-06-18T04:16:27.044Z,https://randomuser.me/api/portraits/women/90.jpg
2,Tyler Rice,57,male,Toowoomba,Northern Territory,tyler.rice@example.com,1969-03-30T22:59:42.933Z,https://randomuser.me/api/portraits/men/12.jpg
3,Sofia Bakkan,51,female,Heggedal,Oppland,sofia.bakkan@example.com,1975-01-02T02:25:20.046Z,https://randomuser.me/api/portraits/women/72.jpg
4,Sander Pedersen,65,male,V.Skerninge,Syddanmark,sander.pedersen@example.com,1961-06-18T20:45:40.755Z,https://randomuser.me/api/portraits/men/24.jpg
5,Matthew Singh,80,male,Notre Dame de Lourdes,Nunavut,matthew.singh@example.com,1946-04-26T12:28:26.023Z,https://randomuser.me/api/portraits/men/36.jpg
6,Kick Gort,31,male,'s-Gravendeel,Drenthe,kick.gort@example.com,1995-02-02T17:16:13.534Z,https://randomuser.me/api/portraits/men/3.jpg
7,Steve Hayes,72,male,Lubbock,Texas,steve.hayes@example.com,1954-05-10T16:16:39.304Z,https://randomuser.me/api/portraits/men/53.jpg
8,Susana Torres,56,female,Murcia,Cataluña,susana.torres@example.com,1970-03-02T15:13:08.228Z,https://randomuser.me/api/portraits/women/10.jpg
9,Orrin Linker,35,male,Ulvenhout Ac,Zeeland,orrin.linker@example.com,1991-01-12T06:05:07.294Z,https://randomuser.me/api/portraits/men/7.jpg

In [77]:
import os
import requests
import json

In [78]:
url_line = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/data/Example1.txt"
r_line = requests.get(url_line)
path = os.path.join(os.getcwd(),'three_line')
with open(path, 'w') as f:
    f.write(r_line.text)
with open(path, 'r') as f:
    print(f.read())

This is line 1
This is line 2
This is line 3

In [1]:
url_fruit = "https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all"
data = requests.get(url_fruit)
data_fruit = json.loads(data.text) #list (dict )
df_data_fruit = pd.DataFrame(data_fruit)
df_data_fruit

NameError: name 'requests' is not defined

In [ ]:
df2 = pd.json_normalize(data_fruit)
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

In [ ]:
cherry = df2.loc[df2['name'] == 'Cherry']
cherry

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.3,8.0,12.0,1.0

In [ ]:
cherry.iloc[0]['family'] #iloc theo vị trí, loc theo tên nhãn

'Rosaceae'

In [83]:
cherry.iloc[0]['family'], cherry.iloc[0]['genus']

('Rosaceae', 'Prunus')

In [84]:
url_jokes = 'https://official-joke-api.appspot.com/jokes/ten'
data = requests.get(url_jokes)
data_jokes = json.loads(data.text)
data_jokes

[{'type': 'general',
  'setup': 'What kind of tree fits in your hand?',
  'punchline': 'A palm tree!',
  'id': 257},
 {'type': 'general',
  'setup': 'Why did the butcher work extra hours at the shop?',
  'punchline': 'To make ends meat.',
  'id': 62},
 {'type': 'general',
  'setup': 'What did the scarf say to the hat?',
  'punchline': 'You go on ahead, I am going to hang around a bit longer.',
  'id': 183},
 {'type': 'general',
  'setup': 'What did the big flower say to the littler flower?',
  'punchline': 'Hi, bud!',
  'id': 167},
 {'type': 'general',
  'setup': "What's the difference between a guitar and a fish?",
  'punchline': 'You can tune a guitar but you can\'t "tuna"fish!',
  'id': 270},
 {'type': 'general',
  'setup': "You see, mountains aren't just funny.",
  'punchline': 'They are hill areas.',
  'id': 400},
 {'type': 'general',
  'setup': "What do you call a bee that can't make up its mind?",
  'punchline': 'A maybe.',
  'id': 372},
 {'type': 'general',
  'setup': 'What kind of magic do cows believe in?',
  'punchline': 'MOODOO.',
  'id': 254},
 {'type': 'general',
  'setup': "What's a computer's favorite snack?",
  'punchline': 'Microchips.',
  'id': 423},
 {'type': 'general',
  'setup': "How do locomotives know where they're going?",
  'punchline': 'Lots of training',
  'id': 119}]

In [88]:
df = pd.DataFrame(data_jokes)
df

,type,setup,punchline,id
0,general,What kind of tree fits in your hand?,A palm tree!,257
1,general,Why did the butcher work extra hours at the shop?,To make ends meat.,62
2,general,What did the scarf say to the hat?,"You go on ahead, I am going to hang around a b...",183
3,general,What did the big flower say to the littler flo...,"Hi, bud!",167
4,general,What's the difference between a guitar and a f...,"You can tune a guitar but you can't ""tuna""fish!",270
5,general,"You see, mountains aren't just funny.",They are hill areas.,400
6,general,What do you call a bee that can't make up its ...,A maybe.,372
7,general,What kind of magic do cows believe in?,MOODOO.,254
8,general,What's a computer's favorite snack?,Microchips.,423
9,general,How do locomotives know where they're going?,Lots of training,119

In [89]:
#df.drop(labels = ['type', 'id'],axis = 1, inplace = True)
df.drop(columns = ['type', 'id'], inplace = True)
df

,setup,punchline
0,What kind of tree fits in your hand?,A palm tree!
1,Why did the butcher work extra hours at the shop?,To make ends meat.
2,What did the scarf say to the hat?,"You go on ahead, I am going to hang around a b..."
3,What did the big flower say to the littler flo...,"Hi, bud!"
4,What's the difference between a guitar and a f...,"You can tune a guitar but you can't ""tuna""fish!"
5,"You see, mountains aren't just funny.",They are hill areas.
6,What do you call a bee that can't make up its ...,A maybe.
7,What kind of magic do cows believe in?,MOODOO.
8,What's a computer's favorite snack?,Microchips.
9,How do locomotives know where they're going?,Lots of training